In [9]:
import cv2 as cv
import numpy as np
import os


In [64]:
# Frame params
FRAME_HEIGHT = 480
FRAME_WIDTH = 640

num_bins_x = 4
num_bins_y = 3

In [65]:
# Create output folder
output_folder = "orb_keypoints"
os.makedirs(output_folder, exist_ok=True)

# Initiate ORB detector
orb = cv.ORB_create(nfeatures=250)

# Storing keypoint data
kp_list = []

# Process images 1 to 10
for i in range(1, 2):
    img_path = rf"Images\img{i:04d}.png"
    
    img = cv.imread(img_path, cv.IMREAD_GRAYSCALE)
    
    if img is None:
        print(f"Failed to load {img_path}")
        continue
    
    # Detect and compute keypoints
    kp = orb.detect(img, None)
    kp, des = orb.compute(img, kp)

    # Save raw keypoints
    kp_list.append(kp)
    
    # Draw keypoints
    img_kp = cv.drawKeypoints(img, kp, None, color=(0,255,0), flags=0)
    
    # Draw grid
    bin_width = FRAME_WIDTH // num_bins_x
    bin_height = FRAME_HEIGHT // num_bins_y
    
    # Vertical lines
    for x in range(0, FRAME_WIDTH + 1, bin_width):
        cv.line(img_kp, (x, 0), (x, FRAME_HEIGHT), (255, 0, 0), 2)
    
    # Horizontal lines
    for y in range(0, FRAME_HEIGHT + 1, bin_height):
        cv.line(img_kp, (0, y), (FRAME_WIDTH, y), (255, 0, 0), 2)
    
    # Save result
    output_path = os.path.join(output_folder, f'kp_img{i:04d}.png')
    cv.imwrite(output_path, img_kp)

print(f"\nAll images saved to: {output_folder}")


All images saved to: orb_keypoints


In [ ]:
x_data = []
y_data = []
for frame in kp_list:
    x_data.extend([kp.pt[0] for kp in frame])
    y_data.extend([kp.pt[1] for kp in frame])

hist, x_edges, y_edges = np.histogram2d(x=x_data, y=y_data, bins=[num_bins_x, num_bins_y], range=[[0, FRAME_HEIGHT], [0, FRAME_WIDTH]])

print(hist)
print(x_edges)
print(y_edges)


[[22.  0.]
 [16.  0.]
 [72.  0.]
 [11.  0.]]
[  0. 120. 240. 360. 480.]
[  0. 320. 640.]


In [61]:
for i in range(len(x_edges) - 1):
    for j in range(len(y_edges) - 1):
        print(f"Point count [[{x_edges[i]:.2f}, {x_edges[i+1]:.2f}], [{y_edges[j]:.2f}, {y_edges[j+1]:.2f}]]: {hist[i, j]}")

Point count [[0.00, 120.00], [0.00, 320.00]]: 22.0
Point count [[0.00, 120.00], [320.00, 640.00]]: 0.0
Point count [[120.00, 240.00], [0.00, 320.00]]: 16.0
Point count [[120.00, 240.00], [320.00, 640.00]]: 0.0
Point count [[240.00, 360.00], [0.00, 320.00]]: 72.0
Point count [[240.00, 360.00], [320.00, 640.00]]: 0.0
Point count [[360.00, 480.00], [0.00, 320.00]]: 11.0
Point count [[360.00, 480.00], [320.00, 640.00]]: 0.0


In [62]:

for frame_idx, keypoints in enumerate(kp_list, start=1):
    print(f"\n--- Frame {frame_idx} ---")
    for kp in keypoints:
        if kp.response >= 0.001:
            print(f"  xy: ({kp.pt[0]:.2f}, {kp.pt[1]:.2f}) -- response: {kp.response:.3f}")


--- Frame 1 ---
  xy: (517.00, 288.00) -- response: 0.001
  xy: (510.00, 277.00) -- response: 0.001
  xy: (338.00, 98.00) -- response: 0.001
  xy: (328.00, 99.00) -- response: 0.002
  xy: (508.00, 279.00) -- response: 0.001
  xy: (327.60, 98.40) -- response: 0.001
  xy: (328.32, 99.36) -- response: 0.001
